model_name: "mistralai/Mistral-7B-Instruct-v0.3"
vector_store_path: "ai_project/data/vector_store.json"
api_key: "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"
temperature: 0.7
cache_dir: "ai_project/data/model_cache"
prompt_template_path: "ai_project/src/prompt/query_template.txt"
